apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
  namespace: test
spec:
  storageClassName: tomcat-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/yaml/tomcat/data-tomcat
